apiVersion: v1
kind: Namespace
metadata:
  name: nginx-app-ns
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-app-ingress
  namespace: nginx-app-ns
spec:
  rules:
  - host: nginxapp.com
    http:
      paths:
        - backend:
            serviceName: nginx-app-service
            servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  namespace: nginx-app-ns
spec:
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-deployment
  namespace: nginx-app-ns
spec:
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: "nginx"
        env:
        - name: "PORT"
          value: "80"